### ISSUE TITLE
Entity sensor.skycooker_rmc_m903s_status cannot be added as the entity category is set to config

### ISSUE THREAD

**Issue by MaiklinHouse** [KomX/ESPHome-Ready4Sky#5]
После обновления до homeassistant:2023.11.0, стали сыпаться ошибки:

2023-11-02 02:14:51.090 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform esphome
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.skycooker_rmc_m903s_status cannot be added as the entity category is set to config

**Comment by MaiklinHouse** [comment]
Заменил в \hassio\addons\data\5c53de3b_esphome\external_components\139c6545\components\skycooker\__init__.py
стр. 388
                cv.Optional(CONF_ENTITY_CATEGORY, default=ENTITY_CATEGORY_CONFIG): cv.entity_category,
на
                cv.Optional(CONF_ENTITY_CATEGORY, default=ENTITY_CATEGORY_DIAGNOSTIC): cv.entity_category,
ошибки пропали и появилась строка состояния в HA
